services:
  api:
    container_name: kroma-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "18080:8080"
    env_file:
      - ./apps/api/.env
    environment:
      - NODE_ENV=production
      - GOOGLE_CALLBACK_URL=http://localhost:18080/v1/auth/google/callback
    depends_on:
      - database
      - worker-image
    networks:
      - saas-image

  worker-image:
    container_name: kroma-worker
    build:
      context: ./apps/worker-image
      dockerfile: Dockerfile
    ports:
      - "18000:8000"
    networks:
      - saas-image

  web:
    container_name: kroma-web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - "13000:3000"
    networks:
      - saas-image

  database:
    image: postgres:17
    container_name: kroma-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - .docker/postgres:/var/lib/postgresql/data
    networks:
      - saas-image

  rabbitmq:
    image: rabbitmq:3-management
    container_name: kroma-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=kroma # Porta do protocolo AMQP (aplicações)
      - RABBITMQ_DEFAULT_PASS=kroma # Painel web de gerenciamento
    volumes:
      - .docker/rabbitmq:/var/lib/rabbitmq
    networks:
      - saas-image
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: pgsty/silo:latest
    container_name: kroma-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # Console Web
    environment:
      - MINIO_ROOT_USER=kromauser
      - MINIO_ROOT_PASSWORD=kromapassword
    volumes:
      - .docker/minio:/data
    networks:
      - saas-image
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  saas-image:
    driver: bridge
